/**
 * exportToPdf
 * Captures a DOM element and downloads it as a PDF.
 * Uses html2canvas + jsPDF (both loaded lazily to avoid SSR issues).
 */
export async function exportToPdf(
  elementId: string,
  filename = "social-growth-ai-report.pdf"
): Promise<void> {
  // Dynamic imports — never run on server
  const [{ default: html2canvas }, { default: jsPDF }] = await Promise.all([
    import("html2canvas"),
    import("jspdf"),
  ]);

  const el = document.getElementById(elementId);
  if (!el) throw new Error(`Element #${elementId} not found`);

  // Temporarily force white bg for screenshot clarity
  const originalBg = el.style.background;
  el.style.background = "#0a0f1e";

  const canvas = await html2canvas(el, {
    scale: 2,
    useCORS: true,
    backgroundColor: "#0a0f1e",
    logging: false,
    windowWidth: el.scrollWidth,
    windowHeight: el.scrollHeight,
  });

  el.style.background = originalBg;

  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF({
    orientation: canvas.width > canvas.height ? "landscape" : "portrait",
    unit: "px",
    format: [canvas.width / 2, canvas.height / 2],
  });

  pdf.addImage(imgData, "PNG", 0, 0, canvas.width / 2, canvas.height / 2);
  pdf.save(filename);
}

/**
 * exportTextToPdf
 * Generates a clean text-based PDF from a plain object — no screenshot needed.
 */
export async function exportTextToPdf(
  title: string,
  sections: { heading: string; body: string }[],
  filename = "social-growth-ai-report.pdf"
): Promise<void> {
  const { default: jsPDF } = await import("jspdf");

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 48;
  const contentW = pageW - margin * 2;
  let y = margin;

  // Header
  doc.setFillColor(12, 15, 30);
  doc.rect(0, 0, pageW, doc.internal.pageSize.getHeight(), "F");
  doc.setTextColor(240, 240, 245);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(title, margin, y);
  y += 10;

  doc.setTextColor(139, 143, 163);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated by Social Growth AI — ${new Date().toLocaleDateString()}`, margin, y + 14);
  y += 40;

  // Divider
  doc.setDrawColor(255, 255, 255, 0.08);
  doc.line(margin, y, pageW - margin, y);
  y += 20;

  for (const section of sections) {
    // Check page space
    if (y > doc.internal.pageSize.getHeight() - margin * 2) {
      doc.addPage();
      doc.setFillColor(12, 15, 30);
      doc.rect(0, 0, pageW, doc.internal.pageSize.getHeight(), "F");
      y = margin;
    }

    // Section heading
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(124, 111, 247);
    doc.text(section.heading, margin, y);
    y += 18;

    // Section body
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(200, 200, 210);
    const lines = doc.splitTextToSize(section.body, contentW);
    doc.text(lines, margin, y);
    y += lines.length * 14 + 16;
  }

  doc.save(filename);
}
